
#[cfg_attr(target_arch = "wasm32", wasm_bindgen::prelude::wasm_bindgen(start))]
pub fn main() {
    /* let ui = Game24App::new();

    ui.on_request_increase_value(move || {
        ui.as_weak().unwrap().set_counter(ui.get_counter() + 1);
    });

    ui.run(); */

    MainWindow::new().run();
}

//slint::include_modules!();  // Include the code generated by slint-build from build.rs
slint::slint! {
    MemoryTile := Rectangle {
        property <bool> open_curtain;
        property <bool> solved;
        property <image> icon;
        callback clicked;

        width:  64px;
        height: 64px;
        border_radius: 2px;
        background: solved ? #34CE57 : #3960D5;
        //animate background { duration: 800ms; }

        Image {
            source: icon;
            width:  parent.width;
            height: parent.height;
        }

        LeftCurtain := Rectangle {
            background: #193076;
            height: parent.height;
            width: open_curtain ? 0px : (parent.width / 2);
            animate width { duration: 250ms; easing: ease-in; }
        }

        RightCurtain := Rectangle {
            height: parent.height;
            background: LeftCurtain.background;
            width: open_curtain ? 0px : (parent.width / 2);
            x: open_curtain ? parent.width : (parent.width / 2);
            animate width { duration: 250ms; easing: ease-in; }
            animate x     { duration: 250ms; easing: ease-in; }
        }

        TouchArea {
            // Delegate to the user of this element
            clicked => { root.clicked(); }
        }
    }

    MainWindow := Window {
        title: "Hello Slint";
        preferred-width: 800px;
        preferred-height: 600px;

        Image {
            source: @image-url("assets/Ghostscript_Tiger.svg");
            width: parent.width / 2;
            x: (parent.width  - width) / 2;
            y: (parent.height - height) / 2;
        }

        //Text { text: "Hello, World!"; color: green; }

        MemoryTile {
            icon: @image-url("assets/icons/bus-solid.svg");
            clicked => { self.open_curtain = !self.open_curtain; }
        }
    }
}

