
# cargo binstall dioxus-cli # dx new foo

[application]
name = "indiox"     # App (Project) name

# you can also use `dx serve/build --platform XXX` to use other platform
default_platform = "web"    # value: web | desktop | mobile

#asset_dir = "assets"       # resource (static) file folder
#out_dir = "dist"    # Web `build` & `serve` dist path
#hot_reload = true   # hot reload by default

[web.wasm_opt]
level = "4"     # The level wasm-opt should target. z is the smallest. 4 is the fastest.

[web.app]
title = "24 Puzzle"     # HTML title tag content
base_path = "inrust/indiox"    # "/"
#index_on_404 = true

[web.watcher]
reload_html = true  # when watcher trigger, regenerate the `index.html`

# which files or dirs will be watcher monitoring
watch_path = [ "src", "assets", "index.html", "tailwind_base.css", "tailwind.config.js" ]

#[web.resource]  # include `assets` in web platform
#style = [ "assets/tailwind.css" ]  # Additional CSS style files
#script = [] # Additional JavaScript files

[web.resource.dev]
script = [] # Javascript code file, serve: [dev-server] only
#script = ["https://cdn.tailwindcss.com"]


